package stocktrade.stocktrade.enums;

public enum Permissions {
    CREATE_PLAN,
    UPDATE_PLAN,
    DELETE_PLAN,

    CREATE_RECOMMENDATION,
    UPDATE_RECOMMENDATION,
    DELETE_RECOMMENDATION,

    PLAN_MASTER,
    RECOMMENDATION_MASTER,

    PLAN_CREATE_DELETE,
    PLAN_CREATE_UPDATE,
    PLAN_UPDATE_DELETE,

    RECOMMENDATION_CREATE_DELETE,
    RECOMMENDATION_CREATE_UPDATE,
    RECOMMENDATION_UPDATE_DELETE,

    VIEW_PLATFORM
}
