package stocktrade.stocktrade.enums;

public enum Permissions {
    CREATE_PLAN,
    UPDATE_PLAN,
    DELETE_PLAN,

    CREATE_RECOMMENDATION,
    UPDATE_RECOMMENDATION,
    DELETE_RECOMMENDATION,

    PLAN_MASTER,
    RECOMMENDATION_MASTER,

    PLAN_UPDATE_DELETE,
    PLAN_UPDATE_ADD_CUSTOMER,
    PLAN_DELETE_ADD_CUSTOMER,



    RECOMMENDATION_CREATE_DELETE,
    RECOMMENDATION_CREATE_UPDATE,
    RECOMMENDATION_UPDATE_DELETE,
    ADD_CUSTOMER_TO_PLAN,

    VIEW_PLATFORM
}
